server:
    port: 8081
    servlet:
      context-path: /springboot
spring:
  profiles:
    active: a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.100.111.5:3306/test
    username: testUser
    password: testPWD#123

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true